[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[colors.bright]
black = "#445371"
blue = "#71A0D0"
cyan = "#83C7C5"
green = "#A1CA7F"
magenta = "#BD84B3"
red = "#D64956"
white = "#EAEEF5"
yellow = "#FFD176"

[colors.cursor]
cursor = "#D3DCED"
text = "#293244"

[colors.dim]
black = "#313B52"
blue = "#5B7FA6"
cyan = "#5F9CB3"
green = "#7D9D6D"
magenta = "#926C92"
red = "#A44451"
white = "#AAB2BE"
yellow = "#C1A365"

[colors.normal]
black = "#353F57"
blue = "#71A0D0"
cyan = "#76C9E2"
green = "#A1CA7F"
magenta = "#BD84B3"
red = "#D64956"
white = "#E2E8F2"
yellow = "#FFD176"

[colors.primary]
background = "#1E1E1E"
dim_foreground = "#B1B1B1"
foreground = "#ABB2BF"

[colors.search.matches]
background = "#88C0D0"
foreground = "CellBackground"

[colors.selection]
background = "#4C566A"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#D3DCED"
text = "#293244"

[font]
size = 12

[font.bold]
family = "RobotoMono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono"
style = "Italic"

[font.normal]
family = "RobotoMono"
style = "Regular"

[window.padding]
x = 15
y = 15

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

# Bindings for Russian layout
[[keyboard.bindings]]
key = "ะก"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "ะ"
mods = "Control|Shift"
action = "Paste"

# [selection]
# save_to_clipboard = true


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
